### ISSUE TITLE
PNG files get encoded

### ISSUE THREAD

**Issue by aleksandarPerc** [disintegrator/grunt-juice-email#11]
I noticed that img elements with a src attribute containing a file with the extension .png get encoded
"src="data:image/png;base64,iVBORw0KGgoAAAANSUhE.........."
Instead of just having a path...
Can this be avoided somehow?

**Comment by adyz** [comment]
I have the same problem, any ideas? Also, I noticed that only simple images get replaced (1 color) and the complex ones keep the source.

Problem in that gmail strips this kind of stuff.

**Comment by adyz** [comment]
@aleksandarPerc add `data-inline-ignore` to the image tag: 

https://github.com/jrit/web-resource-inliner#inlineattribute-string-default-data-inline

**Comment by aleksandarPerc** [comment]
@adyz Many thanks!
